"""Initial database migration based on ERD

Revision ID: 357b13b01e04
Revises: 
Create Date: 2025-10-25 11:32:27.636797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '357b13b01e04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='Prompt này của user nào'),
    sa.Column('major', sa.String(), nullable=False, comment='Ngành học'),
    sa.Column('background', sa.Text(), nullable=True, comment='Background bản thân'),
    sa.Column('self_assessment_level', sa.Enum('beginner', 'intermediate', 'advanced', name='assessment_level_enum'), nullable=False),
    sa.Column('daily_study_hours', sa.Float(), nullable=True, comment='Giờ học trung bình/ngày'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_prior_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_info_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_info_id'], ['book.info_id'], ),
    sa.ForeignKeyConstraint(['id'], ['roadmap_prompt.id'], ),
    sa.PrimaryKeyConstraint('id', 'book_info_id')
    )
    op.create_table('roadmap',
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='Roadmap này được tạo từ prompt nào'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Roadmap này thuộc user nào'),
    sa.Column('title', sa.String(), nullable=True, comment='Tiêu đề của roadmap'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['roadmap_prompt.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('roadmap_id')
    )
    op.create_table('roadmap_node',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False, comment='Node này thuộc roadmap nào'),
    sa.Column('parent_node_id', sa.Integer(), nullable=True, comment='Tự tham chiếu để tạo cây'),
    sa.Column('info_id', sa.Integer(), nullable=True, comment='Nội dung của node (trỏ tới Book hoặc Article)'),
    sa.Column('node_order', sa.Integer(), nullable=True, comment='Thứ tự của node trong cùng 1 cấp'),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Dùng cho soft-deletion (NULL = chưa xóa)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['info_id'], ['textual_information.info_id'], ),
    sa.ForeignKeyConstraint(['parent_node_id'], ['roadmap_node.node_id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.roadmap_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.drop_table('roadmap_nodes')
    op.drop_table('roadmaps')
    op.drop_table('migrations')
    op.drop_table('roadmap_prompts')
    with op.batch_alter_table('roadmap_prompts_has_previously_read_textual_information', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IDX_dde081c076609e36e3fbb8c6af'))
        batch_op.drop_index(batch_op.f('IDX_e4353aadf108aa2cf2b6673409'))

    op.drop_table('roadmap_prompts_has_previously_read_textual_information')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_id', sa.Integer(), nullable=False, comment='Kế thừa từ TextualInformation (TPT)'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('journal_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Tên tạp chí học thuật')
        batch_op.alter_column('doi',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Digital Object Identifier')
        batch_op.alter_column('authors',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('publication_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('FK_40808690eb7b915046558c0f81b'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'textual_information', ['info_id'], ['info_id'])
        batch_op.drop_column('id')
        batch_op.drop_column('publisher')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_id', sa.Integer(), nullable=False, comment='Kế thừa từ TextualInformation (TPT)'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('publication_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('FK_a3afef72ec8f80e6e5c310b28a4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'textual_information', ['info_id'], ['info_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('textual_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_id', sa.Integer(), nullable=False, comment='Primary key chung'))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('source_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True,
               comment='URL gốc được crawl')
        batch_op.alter_column('info_type',
               existing_type=postgresql.ENUM('book', 'article', name='textual_information_info_type_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('modified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               comment='Dùng để tính năm học',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('modified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
        batch_op.alter_column('modified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               comment=None,
               existing_comment='Dùng để tính năm học',
               existing_nullable=True)
        batch_op.drop_column('username')
        batch_op.drop_column('id')

    with op.batch_alter_table('textual_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('textual_information_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.alter_column('modified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('info_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('book', 'article', name='textual_information_info_type_enum'),
               existing_nullable=False)
        batch_op.alter_column('source_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               comment=None,
               existing_comment='URL gốc được crawl')
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('info_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_a3afef72ec8f80e6e5c310b28a4'), 'textual_information', ['id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('publication_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('info_id')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_40808690eb7b915046558c0f81b'), 'textual_information', ['id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('publication_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('authors',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('doi',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='Digital Object Identifier')
        batch_op.alter_column('journal_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='Tên tạp chí học thuật')
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('info_id')

    op.create_table('roadmap_prompts_has_previously_read_textual_information',
    sa.Column('roadmapPromptsId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('textualInformationId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roadmapPromptsId'], ['roadmap_prompts.id'], name=op.f('FK_dde081c076609e36e3fbb8c6af9'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['textualInformationId'], ['textual_information.id'], name=op.f('FK_e4353aadf108aa2cf2b66734098'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roadmapPromptsId', 'textualInformationId', name=op.f('PK_50a65241c2f5b21ead56fcfd95e'))
    )
    with op.batch_alter_table('roadmap_prompts_has_previously_read_textual_information', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IDX_e4353aadf108aa2cf2b6673409'), ['textualInformationId'], unique=False)
        batch_op.create_index(batch_op.f('IDX_dde081c076609e36e3fbb8c6af'), ['roadmapPromptsId'], unique=False)

    op.create_table('roadmap_prompts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roadmap_prompts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('background', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('self_assessment_level', postgresql.ENUM('expert', 'highly_proficient', 'advanced', 'intermediate', 'beginners', name='roadmap_prompts_self_assessment_level_enum'), server_default=sa.text("'beginners'::roadmap_prompts_self_assessment_level_enum"), autoincrement=False, nullable=False),
    sa.Column('daily_study_hours', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='FK_ffc5b3700c10e1d37513f87eb74'),
    sa.PrimaryKeyConstraint('id', name='PK_cd54ada6d6fe7e4d36f91ca77f3'),
    postgresql_ignore_search_path=False
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_8c82d7f526340ab734260ea46be'))
    )
    op.create_table('roadmaps',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roadmaps_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('promptId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['promptId'], ['roadmap_prompts.id'], name='FK_84ef4e7cf44ea46fa4fb1127c7d'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='FK_29f718c5a5cb41f2266d21ba207'),
    sa.PrimaryKeyConstraint('id', name='PK_9b0d527f9c64d15405c21e7ca54'),
    sa.UniqueConstraint('promptId', name='REL_84ef4e7cf44ea46fa4fb1127c7'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('roadmapId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('infoId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['infoId'], ['textual_information.id'], name=op.f('FK_5e9883fe164e9b2ce8a3686bf28')),
    sa.ForeignKeyConstraint(['parentId'], ['roadmap_nodes.id'], name=op.f('FK_a8ad9498b89f9cd2a2e0bc1ed29')),
    sa.ForeignKeyConstraint(['roadmapId'], ['roadmaps.id'], name=op.f('FK_4dbc185f16b2ce3d4306e31f016')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_428aeada0f36f851e12933c1efd'))
    )
    op.drop_table('roadmap_node')
    op.drop_table('roadmap')
    op.drop_table('prompt_prior_reading')
    op.drop_table('roadmap_prompt')
    # ### end Alembic commands ###
